# Generated by Django 2.2.5 on 2019-11-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0026_auto_20191123_1710'),
        ('user', '0007_auto_20191123_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(choices=[(0, 'Не существует'), (1, 'Оскорбительное поведение'), (2, 'Другое')], verbose_name='Причина жалобы на пользователя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(31, 'Новая'), (32, 'Правильная'), (33, 'Ложная')], verbose_name='Статус жалобы на пользователя')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_user_author', to='user.User', verbose_name='Автор жалобы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Пользователь в жалобе')),
            ],
            options={
                'verbose_name': 'Жалобы на ользователей',
                'verbose_name_plural': 'Жалобы-Пользователи',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ComplaintBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.IntegerField(choices=[(0, 'Книга не существует'), (1, 'Оскорбительное содержание'), (2, 'Книга отсутствует у владельца'), (3, 'Другое')], verbose_name='Причина жалобы на книгу')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(31, 'Новая'), (32, 'Правильная'), (33, 'Ложная')], verbose_name='Статус жалобы на книгу')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_book_author', to='user.User', verbose_name='Автор жалобы')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book', verbose_name='Книга в жалобе')),
            ],
            options={
                'verbose_name': 'Жалобы на книги',
                'verbose_name_plural': 'Жалобы-Книги',
                'ordering': ('pk',),
            },
        ),
    ]
