# Generated by Django 2.2.5 on 2019-09-28 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='Обязательное. Не более 30 символов.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Введите имя пользователя. Может содержать только буквы, цифры и символы @/./+/-/_', 'invalid')], verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=30, verbose_name='Пароль')),
            ],
        ),
    ]
