# Generated by Django 2.2.5 on 2019-10-20 08:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191009_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to=user.models.photo_upload_path, verbose_name='Аватар'),
        ),
    ]
