# Generated by Django 2.2.5 on 2019-10-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_django_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
