# Generated by Django 2.2.5 on 2019-10-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191020_1139'),
        ('user', '0003_auto_20191019_1510'),
    ]

    operations = [
    ]
