# Generated by Django 2.2.5 on 2019-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191020_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='URL аватара'),
        ),
    ]
