# Generated by Django 2.2.5 on 2019-10-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191020_1651'),
        ('user', '0004_merge_20191020_1602'),
    ]

    operations = [
    ]
