# Generated by Django 2.2.5 on 2019-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20191021_2228'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='books_given',
        #     field=models.IntegerField(default=0, verbose_name='Книг отдано'),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='books_taken',
        #     field=models.IntegerField(default=0, verbose_name='Книг взято'),
        # ),
    ]
