# Generated by Django 2.2.5 on 2019-11-23 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191110_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='django_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_django', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь django'),
        ),
    ]
