# Generated by Django 2.2.5 on 2019-11-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191123_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notification', models.BooleanField(default=True, verbose_name='Почтовые уведомления')),
                ('email_news', models.BooleanField(default=True, verbose_name='Почтовая рассылка')),
                ('vk_notification', models.BooleanField(default=True, verbose_name='ВК уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Пользователь в рассылке')),
            ],
        ),
    ]
