# Generated by Django 2.2.5 on 2019-11-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ('pk',), 'verbose_name': 'Рассылки пользователей', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
